// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: internal/proto/dispatcherBasketOrder/dispatcherBasketOrder.proto

package dispatcherBasketOrder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BasketOrder
type CreateBasketOrderOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CreateBasketOrderOrderRequest) Reset() {
	*x = CreateBasketOrderOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBasketOrderOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasketOrderOrderRequest) ProtoMessage() {}

func (x *CreateBasketOrderOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasketOrderOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateBasketOrderOrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBasketOrderOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Base
type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDescGZIP(), []int{1}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto protoreflect.FileDescriptor

var file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDesc = []byte{
	0x0a, 0x40, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x72, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x15, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x42, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x1d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x1c, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x32, 0x8b, 0x01, 0x0a, 0x1c, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x6b, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x34, 0x2e, 0x64,
	0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x42,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x42,
	0x19, 0x5a, 0x17, 0x2f, 0x3b, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x42,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDescOnce sync.Once
	file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDescData = file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDesc
)

func file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDescGZIP() []byte {
	file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDescOnce.Do(func() {
		file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDescData)
	})
	return file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDescData
}

var file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_goTypes = []interface{}{
	(*CreateBasketOrderOrderRequest)(nil), // 0: dispatcherBasketOrder.CreateBasketOrderOrderRequest
	(*UUID)(nil),                          // 1: dispatcherBasketOrder.UUID
}
var file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_depIdxs = []int32{
	0, // 0: dispatcherBasketOrder.DispatcherBasketOrderService.CreateBasketOrderOrder:input_type -> dispatcherBasketOrder.CreateBasketOrderOrderRequest
	1, // 1: dispatcherBasketOrder.DispatcherBasketOrderService.CreateBasketOrderOrder:output_type -> dispatcherBasketOrder.UUID
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_init() }
func file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_init() {
	if File_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBasketOrderOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_goTypes,
		DependencyIndexes: file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_depIdxs,
		MessageInfos:      file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_msgTypes,
	}.Build()
	File_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto = out.File
	file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_rawDesc = nil
	file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_goTypes = nil
	file_internal_proto_dispatcherBasketOrder_dispatcherBasketOrder_proto_depIdxs = nil
}
