// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: internal/proto/dispatcherBasketOrder/dispatcherBasketOrder.proto

package dispatcherBasketOrder

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DispatcherBasketOrderServiceClient is the client API for DispatcherBasketOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DispatcherBasketOrderServiceClient interface {
	CreateBasketOrderOrder(ctx context.Context, in *CreateBasketOrderOrderRequest, opts ...grpc.CallOption) (*UUID, error)
}

type dispatcherBasketOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatcherBasketOrderServiceClient(cc grpc.ClientConnInterface) DispatcherBasketOrderServiceClient {
	return &dispatcherBasketOrderServiceClient{cc}
}

func (c *dispatcherBasketOrderServiceClient) CreateBasketOrderOrder(ctx context.Context, in *CreateBasketOrderOrderRequest, opts ...grpc.CallOption) (*UUID, error) {
	out := new(UUID)
	err := c.cc.Invoke(ctx, "/dispatcherBasketOrder.DispatcherBasketOrderService/CreateBasketOrderOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatcherBasketOrderServiceServer is the server API for DispatcherBasketOrderService service.
// All implementations must embed UnimplementedDispatcherBasketOrderServiceServer
// for forward compatibility
type DispatcherBasketOrderServiceServer interface {
	CreateBasketOrderOrder(context.Context, *CreateBasketOrderOrderRequest) (*UUID, error)
	mustEmbedUnimplementedDispatcherBasketOrderServiceServer()
}

// UnimplementedDispatcherBasketOrderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDispatcherBasketOrderServiceServer struct {
}

func (UnimplementedDispatcherBasketOrderServiceServer) CreateBasketOrderOrder(context.Context, *CreateBasketOrderOrderRequest) (*UUID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBasketOrderOrder not implemented")
}
func (UnimplementedDispatcherBasketOrderServiceServer) mustEmbedUnimplementedDispatcherBasketOrderServiceServer() {
}

// UnsafeDispatcherBasketOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatcherBasketOrderServiceServer will
// result in compilation errors.
type UnsafeDispatcherBasketOrderServiceServer interface {
	mustEmbedUnimplementedDispatcherBasketOrderServiceServer()
}

func RegisterDispatcherBasketOrderServiceServer(s grpc.ServiceRegistrar, srv DispatcherBasketOrderServiceServer) {
	s.RegisterService(&DispatcherBasketOrderService_ServiceDesc, srv)
}

func _DispatcherBasketOrderService_CreateBasketOrderOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBasketOrderOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherBasketOrderServiceServer).CreateBasketOrderOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dispatcherBasketOrder.DispatcherBasketOrderService/CreateBasketOrderOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherBasketOrderServiceServer).CreateBasketOrderOrder(ctx, req.(*CreateBasketOrderOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DispatcherBasketOrderService_ServiceDesc is the grpc.ServiceDesc for DispatcherBasketOrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DispatcherBasketOrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dispatcherBasketOrder.DispatcherBasketOrderService",
	HandlerType: (*DispatcherBasketOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBasketOrderOrder",
			Handler:    _DispatcherBasketOrderService_CreateBasketOrderOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/dispatcherBasketOrder/dispatcherBasketOrder.proto",
}
