// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package passwordHasher

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PasswordHashClient is the client API for PasswordHash service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PasswordHashClient interface {
	CreateHash(ctx context.Context, in *CreateHashRequest, opts ...grpc.CallOption) (*CreateHashResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type passwordHashClient struct {
	cc grpc.ClientConnInterface
}

func NewPasswordHashClient(cc grpc.ClientConnInterface) PasswordHashClient {
	return &passwordHashClient{cc}
}

func (c *passwordHashClient) CreateHash(ctx context.Context, in *CreateHashRequest, opts ...grpc.CallOption) (*CreateHashResponse, error) {
	out := new(CreateHashResponse)
	err := c.cc.Invoke(ctx, "/passwordHasher.PasswordHash/CreateHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordHashClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, "/passwordHasher.PasswordHash/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasswordHashServer is the server API for PasswordHash service.
// All implementations must embed UnimplementedPasswordHashServer
// for forward compatibility
type PasswordHashServer interface {
	CreateHash(context.Context, *CreateHashRequest) (*CreateHashResponse, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	mustEmbedUnimplementedPasswordHashServer()
}

// UnimplementedPasswordHashServer must be embedded to have forward compatible implementations.
type UnimplementedPasswordHashServer struct {
}

func (UnimplementedPasswordHashServer) CreateHash(context.Context, *CreateHashRequest) (*CreateHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHash not implemented")
}
func (UnimplementedPasswordHashServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedPasswordHashServer) mustEmbedUnimplementedPasswordHashServer() {}

// UnsafePasswordHashServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PasswordHashServer will
// result in compilation errors.
type UnsafePasswordHashServer interface {
	mustEmbedUnimplementedPasswordHashServer()
}

func RegisterPasswordHashServer(s grpc.ServiceRegistrar, srv PasswordHashServer) {
	s.RegisterService(&PasswordHash_ServiceDesc, srv)
}

func _PasswordHash_CreateHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordHashServer).CreateHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passwordHasher.PasswordHash/CreateHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordHashServer).CreateHash(ctx, req.(*CreateHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordHash_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordHashServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passwordHasher.PasswordHash/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordHashServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PasswordHash_ServiceDesc is the grpc.ServiceDesc for PasswordHash service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PasswordHash_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "passwordHasher.PasswordHash",
	HandlerType: (*PasswordHashServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHash",
			Handler:    _PasswordHash_CreateHash_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _PasswordHash_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/passwordHasher/hasher.proto",
}
